services:
  api:
    build: .
    image: app-api-aio/api
    restart: on-failure
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 8000 --proxy-headers # Development
    # command: uvicorn main:app --workers 2 --host 0.0.0.0 --port 8000 --proxy-headers        # Production
    volumes:
      - ./:/opt/python-projects/apps/
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./env/app.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://127.0.0.1:8000/v1/home/ping || exit 1"]    # Development
      # test: ["CMD", "sh", "-c", "curl -s -f http://buyloli.store/v1/home/ping || exit 1"]  # Production
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      mgdb:
        condition: service_healthy
      # pgdb:
      #  condition: service_healthy
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    image: app-api-aio/worker
    restart: always
    command: python3 /opt/python-projects/apps/worker/worker_main.py
    environment:
    - PYTHONPATH=/opt/python-projects/apps
    volumes:
      - ./:/opt/python-projects/apps/
    env_file:
      - ./env/worker.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mgdb:
        condition: service_healthy
      # pgdb:
      #  condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api
    ports:
      - "80:80"
      # - "443:443"  # Open when use HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 3

  kafka:
    image: bitnamilegacy/kafka:3.6.1
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092" 
    env_file:
      - ./env/worker.env
    volumes:
      - ./kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    mem_limit: 1G       # limit RAM
    cpus: 0.5           # limit 50% in 1 core CPU
    

  # kafka-ui:
    # image: provectuslabs/kafka-ui:v0.7.2
    # container_name: kafka-ui
    # ports:
    #  - "8080:8080"
    # environment:
    #  - KAFKA_CLUSTERS_0_NAME=local
    #  - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    # depends_on:
    #  - kafka

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    env_file:
      - ./env/app.env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD --appendonly no --save 60 1"
    ports:
      - "6379:6379"
    volumes:
      - ./caching:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "PING" ]
      interval: 10s
      timeout: 10s
      retries: 3

  mgdb:
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./mongo_data:/data/db
    command: --quiet
    ports:
      - "127.0.0.1:27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6

  # pgdb:
  #  image: postgres:15-alpine
  #  restart: on-failure
  #  env_file:
  #    - ./env/app.env
  #  volumes:
  #    - ./postgres_data:/var/lib/postgresql/data
  #  ports:
  #    - "127.0.0.1:5432:5432"
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-$${POSTGRES_USER:-postgres}}"]
  #    interval: 60s
  #    timeout: 60s
  #    retries: 6