services:
  api:
    build: .
    image: app-api-aio/api
    restart: on-failure
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --proxy-headers      # Development
    # command: uvicorn main:app --workers 2 --host 0.0.0.0 --port 8000 --proxy-headers # Production
    volumes:
      - ./:/opt/python-project/app/
    ports:
      - "8000:8000"
    env_file:
      - ./env/app.env
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://api:8000/v1/home/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      mgdb:
        condition: service_healthy
      pgdb:
        condition: service_healthy

  worker:
    build: .
    image: app-api-aio/worker
    restart: on-failure
    command: python3 /opt/python-project/app/worker/worker_main.py
    environment:
    - PYTHONPATH=/opt/python-project/app
    volumes:
      - ./:/opt/python-project/app/
    env_file:
      - ./env/worker.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mgdb:
        condition: service_healthy
      pgdb:
        condition: service_healthy

  nginx:
    image: nginx:1.29.3-alpine
    container_name: nginx-container
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"  # When use HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/nginx-test"]
      interval: 30s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: rabbitmq-container
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 3

  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka-container
    restart: unless-stopped
    ports:
      - "9092:9092"
    env_file:
      - ./env/worker.env
    volumes:
      - kafkadata:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092 > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20

  redis:
    image: redis:8.2.2-alpine
    container_name: redis-container
    restart: unless-stopped
    env_file:
      - ./env/app.env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD --appendonly no --save"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "PING" ]
      interval: 10s
      timeout: 10s
      retries: 3
  
  pgdb:
    image: postgres:18-alpine
    container_name: postgre-container
    restart: unless-stopped
    env_file:
      - ./env/app.env
    volumes:
      - postgredata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-$${POSTGRES_USER:-postgres}}"]
      interval: 60s
      timeout: 60s
      retries: 6

  mgdb:
    image: mongo:8.0.15
    container_name: mongo-container
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    command: --quiet
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1"]
      interval: 60s
      timeout: 60s
      retries: 6
  
  kafbat:
    image: kafbat/kafka-ui:v1.3.0
    container_name: kafbat-container
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ./env/worker.env
    depends_on:
      kafka:
        condition: service_healthy
        
volumes:
  rabbitmqdata:
  kafkadata:
  redisdata:
  postgredata:
  mongodata: